from dataclasses import dataclass
import numpy as np

@dataclass
class Codebook:
    """
    Uniform representation of a model's codebook (shared parameters).
    """
    arrays: list[np.ndarray]

    @property
    def n_bytes(self) -> int:
        """
        Total size in bytes of all arrays composing the codebook.
        We assume float32 precision (4 bytes per value) for all parameters,
        consistent with standard model storage formats.
        """
        return sum(arr.size * 4 for arr in self.arrays)


@dataclass
class Latent:
    """
    Uniform representation of the latent space generated by a model.
    """
    array: np.ndarray
    nature: str  # 'discrete' or 'continuous'

    @property
    def n_bytes(self) -> int:
        """
        Theoretical total size in bytes required to store the latent space.
        For a discrete space, optimal integer coding is simulated (uint8, uint16, uint32).
        For a continuous space, float32 precision (4 bytes) is assumed as the standard storage format.
        """
        if self.nature == "discrete":
            # Determine how many unique values exist (e.g. K clusters)
            num_classes = len(np.unique(self.array))
            if num_classes <= 256:
                return self.array.size * 1  # 1 byte (uint8)
            elif num_classes <= 65536:
                return self.array.size * 2  # 2 bytes (uint16)
            else:
                return self.array.size * 4  # 4 bytes (uint32)
        else:
            # We assume float32 (4 bytes per value) as the optimal continuous storage precision,
            # regardless of whether NumPy computed the values in float64 for numerical stability.
            return self.array.size * 4


def compression_report(
    codebook: Codebook,
    latent: Latent,
    X_original: np.ndarray,
    X_reconstructed: np.ndarray
) -> dict:
    """
    Computes compression evaluation metrics for any algorithm.

    Args:
        codebook: The codebook object containing the shared parameters.
        latent: The latent space object.
        X_original: The initial data of shape (N, D).
        X_reconstructed: The reconstructed data of shape (N, D).

    Returns:
        dict: A dictionary containing the evaluated criteria.
    """
    # Reconstruction quality via Mean Squared Error (MSE)
    mse = np.mean((X_original - X_reconstructed) ** 2)

    # Storage weights
    codebook_size = codebook.n_bytes
    latent_size = latent.n_bytes
    total_size = codebook_size + latent_size

    # Original size in bytes
    original_size = X_original.nbytes

    # Compression ratio
    compression_ratio = original_size / total_size if total_size > 0 else float('inf')

    return {
        "latent_nature": latent.nature,
        "codebook_bytes": codebook_size,
        "latent_bytes": latent_size,
        "total_compressed_bytes": total_size,
        "original_bytes": original_size,
        "compression_ratio": compression_ratio,
        "reconstruction_mse": float(mse)
    }
